name: Pylint

on:
  workflow_dispatch:
  push:
    paths:
      - grabbit
      - tests

jobs:
  run:
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
        poetry-version: ["latest", "2.1.2"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }} and Poetry ${{ matrix.poetry-version }}
      uses: ./.github/actions/setup-python-and-poetry
      with:
        python-version: ${{ matrix.python-version }}
        poetry-version: ${{ matrix.poetry-version }}
    - name: Run Pylint
      run: poetry run pylint $(git ls-files '*.py')