name: Pylint

on:
  workflow_dispatch:
  push:
    paths:
      - grabbit
      - tests

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up latest Python and Poetry
      uses: ./.github/actions/setup-python-and-poetry
      with:
        python-version: "3.x"
        poetry-version: "latest"
    - name: Run Pylint
      run: poetry run pylint $(git ls-files '*.py')
